/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Wed Dec 11 00:18:40 2019. */

#include "protocol.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SimpleMessage_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SimpleMessage, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, SimpleMessage, num, id, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, SimpleMessage, str, num, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, SimpleMessage, num2, str, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, SimpleMessage, num3_add, num2, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
